name: Deployment

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v2

      - name: setup nodejs
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run the tests and generate coverage report
        run: npm test -- --coverage

      - name: Build
        run: npm run build

      - name: Generate deployment package
        run: zip -r deploy.zip ./

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: My-web
          environment_name: My-web-env
          existing_bucket_name: elasticbeanstalk-us-east-1-343032159914
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
